# Generated by Django 5.2.11 on 2026-02-14 02:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='流水线名称')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='projects.project')),
            ],
            options={
                'db_table': 'cicd_pipelines',
            },
        ),
        migrations.CreateModel(
            name='BuildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.CharField(max_length=100, verbose_name='版本/分支')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('aborted', '终止')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('sonar_task_id', models.CharField(blank=True, max_length=100)),
                ('sonar_quality_gate', models.CharField(blank=True, max_length=50)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('log_file', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='ci_cd.pipeline')),
            ],
            options={
                'db_table': 'cicd_builds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='阶段名称')),
                ('order', models.IntegerField(verbose_name='执行顺序')),
                ('script', models.TextField(blank=True, verbose_name='执行脚本')),
                ('timeout', models.IntegerField(default=3600, verbose_name='超时(秒)')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='ci_cd.pipeline')),
            ],
            options={
                'db_table': 'cicd_stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BuildStageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('aborted', '终止')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log_snippet', models.TextField(blank=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_records', to='ci_cd.buildrecord')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci_cd.pipelinestage')),
            ],
            options={
                'db_table': 'cicd_build_stages',
            },
        ),
    ]
