# Generated by Django 5.2.11 on 2026-02-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用统一认证')),
                ('auth_type', models.CharField(choices=[('local', '本地认证'), ('ldap', 'LDAP'), ('keycloak', 'Keycloak (OIDC)'), ('cas', 'CAS')], default='local', max_length=20, verbose_name='认证类型')),
                ('ldap_server_uri', models.CharField(blank=True, max_length=255, verbose_name='LDAP服务器地址')),
                ('ldap_bind_dn', models.CharField(blank=True, max_length=255, verbose_name='LDAP绑定DN')),
                ('ldap_bind_password', models.CharField(blank=True, max_length=255, verbose_name='LDAP绑定密码')),
                ('ldap_user_base_dn', models.CharField(blank=True, max_length=255, verbose_name='用户基础DN')),
                ('ldap_user_filter', models.CharField(blank=True, default='(uid=%(user)s)', max_length=255, verbose_name='用户过滤器')),
                ('ldap_group_base_dn', models.CharField(blank=True, max_length=255, verbose_name='组基础DN')),
                ('ldap_group_filter', models.CharField(blank=True, max_length=255, verbose_name='组过滤器')),
                ('oidc_server_url', models.CharField(blank=True, max_length=255, verbose_name='OIDC服务器地址')),
                ('oidc_realm', models.CharField(blank=True, max_length=100, verbose_name='Realm名称')),
                ('oidc_client_id', models.CharField(blank=True, max_length=100, verbose_name='Client ID')),
                ('oidc_client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret')),
                ('oidc_public_key', models.TextField(blank=True, verbose_name='OIDC公钥')),
                ('cas_server_url', models.CharField(blank=True, max_length=255, verbose_name='CAS服务器地址')),
                ('cas_version', models.CharField(blank=True, default='3', max_length=10, verbose_name='CAS版本')),
                ('auto_create_user', models.BooleanField(default=True, verbose_name='自动创建用户')),
                ('update_user_info', models.BooleanField(default=True, verbose_name='每次登录更新用户信息')),
                ('sync_groups', models.BooleanField(default=False, verbose_name='同步用户组')),
            ],
            options={
                'verbose_name': '统一认证配置',
                'db_table': 'auth_unified_config',
            },
        ),
    ]
