FROM python:3.11
WORKDIR /app
RUN apt-get update && apt-get install -y gcc libpq-dev netcat* && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN chmod +x /app/scripts/entrypoint-celery.sh
ENTRYPOINT ["/app/scripts/entrypoint-celery.sh"]
