# Generated by Django 5.2.11 on 2026-02-14 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='环境名')),
                ('server_ips', models.TextField(verbose_name='服务器IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'environments',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='应用名')),
                ('git_repo', models.URLField(verbose_name='Git仓库地址')),
                ('git_path', models.CharField(default='/', max_length=500, verbose_name='仓库内路径')),
                ('deploy_dir', models.CharField(max_length=500, verbose_name='部署目录')),
                ('start_script', models.CharField(max_length=500, verbose_name='启动脚本')),
                ('stop_script', models.CharField(max_length=500, verbose_name='停止脚本')),
                ('start_cron', models.CharField(blank=True, max_length=100, verbose_name='启动Cron')),
                ('stop_cron', models.CharField(blank=True, max_length=100, verbose_name='停止Cron')),
                ('sonarqube_url', models.URLField(blank=True, verbose_name='SonarQube项目地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.environment')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
