# Generated by Django 5.2.11 on 2026-02-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='projects.project')),
            ],
            options={
                'db_table': 'risk_alerts',
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0, verbose_name='综合风险分')),
                ('code_quality_score', models.FloatField(default=0.0, verbose_name='代码质量分')),
                ('vulnerability_score', models.FloatField(default=0.0, verbose_name='漏洞风险分')),
                ('pipeline_health_score', models.FloatField(default=0.0, verbose_name='流水线健康分')),
                ('last_scan_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='projects.project')),
            ],
            options={
                'db_table': 'risk_profiles',
            },
        ),
    ]
